### ISSUE TITLE
buildconfig : The term 'buildconfig' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. 

### ISSUE THREAD

**Issue by neeteshp** [smnh/single-config#17]
I'm getting this error while executing buildconfig --input=./config.json --output=./config.js --env=development

I did it after installing single-config

**Comment by smnh** [comment]
How did you install the `buildconfig`?
Did you run `npm i -g single-config`?

**Comment by neeteshp** [comment]
By default it gets installed @ C:\Users\User\AppData\Roaming\npm. How to add that under Path Env Variable ?

**Comment by smnh** [comment]
I am not aware of how npm links paths of globally installed modules.
Try adding that folder to your user PATH environment variable.
Maybe this can help: https://stackoverflow.com/questions/9587665/nodejs-cannot-find-installed-module-on-windows

**Comment by neeteshp** [comment]
Thanks @smnh , it worked, closing this issue.
